### ISSUE TITLE
look

### ISSUE THREAD

**Issue by Roxothefluff** [AwesomeParley/BlueyBot#1]
![image_2024-08-07_113044641](https://github.com/user-attachments/assets/800d8c74-8643-4f07-91ec-b4afa670b59c)

**Comment by ParlDev** [comment]
I'm gonna guess there may have been an extra character or something (maybe a space) that was put accidentally when you copied the token, but I'm not sure. 
It could also just be that there was an error on the side of Discord. There also might be an issue with the token itself being incorrect; maybe try copying the token from the developer portal again?
